name = "Gearhaven 齿轮星都"
author = "Unda Rubra"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8bd5bf3d632aaf34da25ebb84532b6e8b63889fa78811b48cd6f050f8a7d556"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
