name = "Gearhaven 齿轮星都"
author = "Unda Rubra"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c875522e9b23cb2ca6607b305c7b5674baf752e66a80daf4d862de06d9c5044c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
