name = "Gearhaven 齿轮星都"
author = "Unda Rubra"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afcdb10dd7e5a42deac074239e6dc0887c9da26e4b83b1f912e1d9a05390d483"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
