VersionLiteLoader:False
Info:正式版 1.21.1, NeoForge 21.1.248
VersionRamCustom:25
VersionVanilla:21.0.1
VersionRamType:1
VersionVanillaName:1.21.1
ReleaseTime:2024-08-08 20:24
VersionNeoForge:21.1.248
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/NeoForge.png
VersionArgumentIndieV2:True
State:7
